### ISSUE TITLE
Add a feature that will count the days in between the 2 dates 

### ISSUE THREAD

**Issue by venkata-penumatsa** [bradgarropy/use-countdown#19]
Hi Team,

Would you like to add a feature that will automatically count the days in between 2 dates?

Thanks
Venkata

**Comment by bradgarropy** [comment]
Do you have any suggestions for the API? Here is what we currently offer with `minutes` and `seconds`.

```javascript
    const countdown = useCountdown({
        minutes: 1,
        seconds: 30,
        format: "mm:ss",
        onCompleted: () => console.log("onCompleted"),
    })
```

Maybe instead of supporting two more date fields, I make this API more generic and allow for a `duration` field instead.

```javascript
    const countdown = useCountdown({
        duration: 1000,
        format: "mm:ss",
        onCompleted: () => console.log("onCompleted"),
    })
```

That way it can support literally anything! For your use case you could use [`date-fns`](https://date-fns.org/) or really just the `Date` object to calculate the duration between two dates.

While this would be a breaking change, I think it offers more flexibility. Do you have any thoughts @penumatv?

**Comment by bradgarropy** [comment]
@penumatv Given that it's been a month since this request and there has been no comment, I'm going to close this issue.

Feel free to reopen if you feel strongly about this!
